[config]
default_to_workspace = false

[tasks.all]
dependencies = [
    "build-all",
    "cbindgen"
]

[tasks.build]
disabled = true

[tasks.build-all]
# disabled = true
dependencies = [
    "build-x86",
    "build-x64",
    "cbindgen"
]

[tasks.build-x86]
command = "cargo"
args = [
    "rustc",
    "--crate-type=cdylib",
    "--target=i686-pc-windows-msvc",
    "--release",
]

[tasks.build-x64]
command = "cargo"
args = [
    "rustc",
    "--crate-type=cdylib",
    "--target=x86_64-pc-windows-msvc",
    "--release",
]

[tasks.cbindgen]
dependencies = [
    "cbindgen-c",
    "cbindgen-cpp",
]

[tasks.cbindgen-c]
command = "cbindgen"
args = [
    "--config",
    "cbindgen.toml",
    "--lang",
    "C",
    "--output",
    "include/xtr/xtr.h"
]

[tasks.cbindgen-cpp]
command = "cbindgen"
args = [
    "--config",
    "cbindgen.toml",
    "--lang",
    "C++",
    "--output",
    "include/xtr/xtr.hpp"
]
