[package]
name = "xtr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
bytes = "1.1"
crossbeam = "0.8"
futures = "0.3"
log = "0.4"
tokio = { version = "1.17", features = ["full"] }

[dev-dependencies]
env_logger = "0.9"
